import Vue from 'vue'
import Vuex from 'vuex'
// import * as firebase from 'firebase'

Vue.use(Vuex)

export default new Vuex.Store({
    state: {
        matchType: 'all',
        players: [
            {name: 'Magdalena Puter', number: '8'},
            {name: 'Aisza Buczek', number: '4'},
            {name: 'Monika Malinowska', number: '24'},
            {name: 'Wiktoria Zając', number: '6'},
            {name: 'Karolina Przybyła', number: '23'},
            {name: 'Gabriela Czekaj', number: '34'},
            {name: 'Natalia Mazur', number: '7'},
            {name: 'Agnieszka Blum', number: '13'},
            {name: 'Dorota Świercz', number: '14'},
            {name: 'Aleksandra Klimas', number: '1'},
            {name: 'Julia Fortuna', number: '5'},
            {name: 'Gabriela Rak', number: '15'},
            {name: 'Julia Natkaniec', number: '12'},
            {name: 'Agnieszka Krawiec', number: '9'},
        ],
        mosirGames: [
            {
                id: 1,
                category: 'homeGame',
                date: '12.06.19',
                points: 60,
                oneM: 9,
                oneA: 13,
                twoM: 30,
                twoA: 45,
                threeM: 9,
                threeA: 22,
                assist: 14,
                fouls: 18,
                turnovers: 6,
                dReb: 12,
                ofReb: 5,
                players: [
                    {
                        points: 10,
                        oneM: 2,
                        oneA: 3,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 4,
                        assist: 1,
                        fouls: 3,
                        turnovers: 2,
                        dReb: 2,
                        ofReb: 7,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        twoM: 4,
                        twoA: 8,
                        threeM: 1,
                        threeA: 4,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 8,
                        oneM: 1,
                        oneA: 2,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 5,
                        assist: 4,
                        fouls: 3,
                        turnovers: 5,
                        dReb: 1,
                        ofReb: 1,
                    },
                    {
                        points: 10,
                        oneM: 2,
                        oneA: 3,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 4,
                        assist: 1,
                        fouls: 3,
                        turnovers: 2,
                        dReb: 2,
                        ofReb: 7,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        twoM: 4,
                        twoA: 8,
                        threeM: 1,
                        threeA: 4,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 8,
                        oneM: 1,
                        oneA: 2,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 5,
                        assist: 4,
                        fouls: 3,
                        turnovers: 5,
                        dReb: 1,
                        ofReb: 1,
                    },
                    {
                        points: 10,
                        oneM: 2,
                        oneA: 3,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 4,
                        assist: 1,
                        fouls: 3,
                        turnovers: 2,
                        dReb: 2,
                        ofReb: 7,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        twoM: 4,
                        twoA: 8,
                        threeM: 1,
                        threeA: 4,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 8,
                        oneM: 1,
                        oneA: 2,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 5,
                        assist: 4,
                        fouls: 3,
                        turnovers: 5,
                        dReb: 1,
                        ofReb: 1,
                    },
                    {
                        points: 10,
                        oneM: 2,
                        oneA: 3,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 4,
                        assist: 1,
                        fouls: 3,
                        turnovers: 2,
                        dReb: 2,
                        ofReb: 7,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        twoM: 4,
                        twoA: 8,
                        threeM: 1,
                        threeA: 4,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 8,
                        oneM: 1,
                        oneA: 2,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 5,
                        assist: 4,
                        fouls: 3,
                        turnovers: 5,
                        dReb: 1,
                        ofReb: 1,
                    },
                    {
                        points: 10,
                        oneM: 2,
                        oneA: 3,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 4,
                        assist: 1,
                        fouls: 3,
                        turnovers: 2,
                        dReb: 2,
                        ofReb: 7,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        twoM: 4,
                        twoA: 8,
                        threeM: 1,
                        threeA: 4,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                ]

            },
            {
                id: 2,
                category: 'awayGame',
                date: '16.08.19',
                points: 48,
                oneM: 9,
                oneA: 13,
                twoM: 30,
                twoA: 45,
                threeM: 9,
                threeA: 22,
                assist: 14,
                fouls: 18,
                turnovers: 6,
                dReb: 12,
                ofReb: 5,
                players: [
                    {
                        points: 10,
                        oneM: 2,
                        oneA: 3,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 4,
                        assist: 1,
                        fouls: 3,
                        turnovers: 2,
                        dReb: 2,
                        ofReb: 7,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        twoM: 4,
                        twoA: 8,
                        threeM: 1,
                        threeA: 4,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 8,
                        oneM: 1,
                        oneA: 2,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 5,
                        assist: 4,
                        fouls: 3,
                        turnovers: 5,
                        dReb: 1,
                        ofReb: 1,
                    },
                    {
                        points: 10,
                        oneM: 2,
                        oneA: 3,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 4,
                        assist: 1,
                        fouls: 3,
                        turnovers: 2,
                        dReb: 2,
                        ofReb: 7,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        twoM: 4,
                        twoA: 8,
                        threeM: 1,
                        threeA: 4,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 8,
                        oneM: 1,
                        oneA: 2,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 5,
                        assist: 4,
                        fouls: 3,
                        turnovers: 5,
                        dReb: 1,
                        ofReb: 1,
                    },
                    {
                        points: 10,
                        oneM: 2,
                        oneA: 3,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 4,
                        assist: 1,
                        fouls: 3,
                        turnovers: 2,
                        dReb: 2,
                        ofReb: 7,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        twoM: 4,
                        twoA: 8,
                        threeM: 1,
                        threeA: 4,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 8,
                        oneM: 1,
                        oneA: 2,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 5,
                        assist: 4,
                        fouls: 3,
                        turnovers: 5,
                        dReb: 1,
                        ofReb: 1,
                    },
                    {
                        points: 10,
                        oneM: 2,
                        oneA: 3,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 4,
                        assist: 1,
                        fouls: 3,
                        turnovers: 2,
                        dReb: 2,
                        ofReb: 7,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        twoM: 4,
                        twoA: 8,
                        threeM: 1,
                        threeA: 4,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 8,
                        oneM: 1,
                        oneA: 2,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 5,
                        assist: 4,
                        fouls: 3,
                        turnovers: 5,
                        dReb: 1,
                        ofReb: 1,
                    },
                    {
                        points: 10,
                        oneM: 2,
                        oneA: 3,
                        twoM: 2,
                        twoA: 5,
                        threeM: 1,
                        threeA: 4,
                        assist: 1,
                        fouls: 3,
                        turnovers: 2,
                        dReb: 2,
                        ofReb: 7,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        twoM: 4,
                        twoA: 8,
                        threeM: 1,
                        threeA: 4,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                ]

            },
        ],
        oppGames: [
            {
                id: 1,
                name: 'Niepołomice',
                points: 42,
                oneM: 9,
                oneA: 13,
                twoM: 32,
                twoA: 40,
                threeM: 9,
                threeA: 25,
                assist: 14,
                fouls: 18,
                turnovers: 6,
                dReb: 7,
                ofReb: 6,
            },
            {
                id: 2,
                name: 'Wisła Canpak',
                points: 59,
                oneM: 9,
                oneA: 13,
                twoM: 32,
                twoA: 40,
                threeM: 9,
                threeA: 25,
                assist: 14,
                fouls: 18,
                turnovers: 6,
                dReb: 7,
                ofReb: 6,

            },
            {
                id: 3,
                name: 'Testowa drużyna',
                points: 47,
                oneM: 9,
                oneA: 13,
                twoM: 32,
                twoA: 40,
                threeM: 9,
                threeA: 25,
                assist: 14,
                fouls: 18,
                turnovers: 6,
                dReb: 7,
                ofReb: 6,
            }
        ]
    },
    getters: {
        games(state) {
            return state.mosirGames.map((mosir, i) => {
                return {
                    mosir: mosir,
                    opponent: state.oppGames[i]
                }
            })
        },
        playerStats(state) {
            return state.mosirGames[0].players.map((playersStats, i) => {
                return {
                    playersStats: playersStats,
                    players: state.players[i]
                }
            })
        },
        mRebs(state) {
            return state.mosirGames[0].dReb + state.mosirGames[0].ofReb
        },
        oRebs(state) {
            return state.oppGames[0].dReb + state.oppGames[0].ofReb
        },
        mFGM(state) {
            return state.mosirGames[0].twoM + state.mosirGames[0].threeM
        },
        oFGM(state) {
            return state.oppGames[0].twoM + state.oppGames[0].threeM
        },
        mFGA(state) {
            return state.mosirGames[0].twoA + state.mosirGames[0].threeA
        },
        oFGA(state) {
            return state.oppGames[0].twoA + state.oppGames[0].threeA
        }


    },
    mutations: {
        SET_MATCH_TYPE(state, payload) {
            state.matchType = payload
        },
        CREATE_MATCH(state, payload){
            state.mosirGames.push(payload)
        }

    },
    actions: {
        CREATE_MATCH({commit},payload){
            const mosirGame ={
                    id: 3,
                    category: payload.selectMatch,
                    date: payload.date,
                    points: payload.points,
                    oneM: payload.oneM,
                    oneA: payload.oneA,
                    twoM: payload.twoM,
                    twoA: payload.twoA,
                    threeM: payload.threeM,
                    threeA: payload.threeA,
                    assist: payload.assist,
                    fouls: payload.fouls,
                    turnovers: payload.turnovers,
                    dReb: payload.dReb,
                    ofReb: payload.ofReb,
                    players: payload.mPlayers
            }
            commit('CREATE_MATCH', mosirGame)
        }
    },
    modules: {}
})
