import Vue from 'vue'
import Vuex from 'vuex'
// import * as firebase from 'firebase'

Vue.use(Vuex)

export default new Vuex.Store({
    state: {
        teams: ['MKS Pałac Młodzieży Tarnów','UKS Żak Nowy Sącz','MTS Ikar Niepołomice', 'Wisła CANPACK Kraków', 'MLKS-MOS Rzeszów', 'KK UR Kraków'],
        matchType: 'all',
        tableHedaers:[
            {
                text: 'Numer',
                align: 'left',
                value: 'playerDetails.number',
            },
            { text: 'Nazwisko', value: 'playerDetails.name', sortable: false },
            { text: 'Punkty', value: 'stats.points' },
            { text: 'Asysty', value: 'stats.assist' },
            { text: 'Straty', value: 'stats.turnovers' },
            { text: 'Faule', value: 'stats.fouls' },
            { text: 'Tr za 1', value: 'stats.oneM' },
            { text: 'P za 1', value: 'stats.oneA' },
            { text: '% za 1', value: 'stats.oneP' },
            { text: 'Tr za 2', value: 'stats.twoM' },
            { text: 'P za 2', value: 'stats.twoA' },
            { text: '% za 2', value: 'stats.twoP' },
            { text: 'Tr za 3', value: 'stats.threeM' },
            { text: 'P za 3', value: 'stats.threeA' },
            { text: '% za 3', value: 'stats.threeP' },
            { text: 'Zb of', value: 'stats.ofReb' },
            { text: 'Zb def', value: 'stats.dReb' },
        ],
        players: [
            {name: 'Magdalena Puter', number: '8'},
            {name: 'Aisza Buczek', number: '4'},
            {name: 'Monika Malinowska', number: '24'},
            {name: 'Wiktoria Zając', number: '6'},
            {name: 'Karolina Przybyła', number: '23'},
            {name: 'Gabriela Czekaj', number: '34'},
            {name: 'Natalia Mazur', number: '7'},
            {name: 'Agnieszka Blum', number: '13'},
            {name: 'Dorota Świercz', number: '14'},
            {name: 'Aleksandra Klimas', number: '1'},
            {name: 'Julia Fortuna', number: '5'},
            {name: 'Gabriela Rak', number: '15'},
            {name: 'Julia Natkaniec', number: '12'},
            {name: 'Agnieszka Krawiec', number: '9'},
        ],
        mosirGames: [
            {
                id: 1,
                category: 'homeGame',
                date: '12.06.19',
                points: 60,
                oneM: 9,
                oneA: 13,
                oneP: 70,
                twoM: 30,
                twoA: 45,
                twoP: 45,
                threeM: 9,
                threeA: 22,
                threeP: 22,
                assist: 14,
                fouls: 18,
                turnovers: 6,
                dReb: 12,
                ofReb: 5,
                players: [
                    {
                        points: 10,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 12,
                        oneM: 5,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 48,
                        threeM: 1,
                        threeA: 4,
                        threeP: 22,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 25,
                        oneM: 3,
                        oneA: 6,
                        oneP: 50,
                        twoM: 4,
                        twoA: 8,
                        twoP: 80,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                ]

            },
            {
                id: 2,
                category: 'awayGame',
                date: '12.06.19',
                points: 60,
                oneM: 9,
                oneA: 13,
                oneP: 70,
                twoM: 30,
                twoA: 45,
                twoP: 45,
                threeM: 9,
                threeA: 22,
                threeP: 22,
                assist: 14,
                fouls: 18,
                turnovers: 6,
                dReb: 12,
                ofReb: 5,
                players: [
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                    {
                        points: 15,
                        oneM: 3,
                        oneA: 5,
                        oneP: 80,
                        twoM: 4,
                        twoA: 8,
                        twoP: 60,
                        threeM: 1,
                        threeA: 4,
                        threeP: 33,
                        assist: 2,
                        fouls: 1,
                        turnovers: 2,
                        dReb: 3,
                        ofReb: 5,
                    },
                ]

            },
        ],
        oppGames: [
            {
                id: 1,
                name: 'Niepołomice',
                points: 42,
                oneM: 9,
                oneA: 13,
                oneP: 13,
                twoM: 32,
                twoA: 40,
                twoP: 40,
                threeM: 9,
                threeA: 25,
                threeP: 30,
                assist: 14,
                fouls: 18,
                turnovers: 6,
                dReb: 7,
                ofReb: 6,
            },
            {
                id: 2,
                name: 'Wisła Canpak',
                points: 60,
                oneM: 9,
                oneA: 13,
                oneP: 70,
                twoM: 30,
                twoA: 45,
                twoP: 45,
                threeM: 9,
                threeA: 22,
                threeP: 30,
                assist: 14,
                fouls: 18,
                turnovers: 6,
                dReb: 12,
                ofReb: 5,

            },
        ]
    },
    getters: {
        games(state) {
            return state.mosirGames.map((mosir, i) => {
                return {
                    mosir: mosir,
                    opponent: state.oppGames[i]
                }
            })
        },

    },
    mutations: {
        SET_MATCH_TYPE(state, payload) {
            state.matchType = payload
        },
        CREATE_MATCH(state, payload){
            state.mosirGames.push(payload)
        },
        CREATE_MATCH_OPP(state, payload){
            state.oppGames.push(payload)
        }

    },
    actions: {
        CREATE_MATCH({commit},payload){
            const mosirGame ={
                    id: 3,
                    category: payload.selectMatch,
                    date: payload.date,
                    points: payload.points,
                    oneM: payload.oneM,
                    oneA: payload.oneA,
                    oneP: (payload.oneM / payload.oneA *100).toFixed(1),
                    twoM: payload.twoM,
                    twoA: payload.twoA,
                    twoP: (payload.twoM / payload.twoA *100).toFixed(1),
                    threeM: payload.threeM,
                    threeA: payload.threeA,
                    threeP: (payload.threeM / payload.threeA *100).toFixed(1),
                    assist: payload.assist,
                    fouls: payload.fouls,
                    turnovers: payload.turnovers,
                    dReb: payload.dReb,
                    ofReb: payload.ofReb,
                    players: payload.mPlayers
            }
            commit('CREATE_MATCH', mosirGame)
        },
        CREATE_MATCH_OPP({commit},payload){
            const oppGames ={
                    id: 3,
                    name:payload.name,
                    points: payload.points,
                    oneM: payload.oneM,
                    oneA: payload.oneA,
                    oneP: (payload.oneM / payload.oneA *100).toFixed(1),
                    twoM: payload.twoM,
                    twoA: payload.twoA,
                    twoP: (payload.twoM / payload.twoA *100).toFixed(1),
                    threeM: payload.threeM,
                    threeA: payload.threeA,
                    threeP: (payload.threeM / payload.threeA *100).toFixed(1),
                    assist: payload.assist,
                    fouls: payload.fouls,
                    turnovers: payload.turnovers,
                    dReb: payload.dReb,
                    ofReb: payload.ofReb,

            }
            commit('CREATE_MATCH_OPP', oppGames)
        },
    },
    modules: {}
})
